-- ============================================================
-- Seed: Departamentos y Ciudades de Paraguay
-- Fuente: ciudadespy.sql + departamentospy.sql (convertido de MySQL)
-- Encoding fixes: Ñumí (id 138), Tte. Irala Fernández (id 224)
-- ============================================================

-- DEPARTAMENTOS
INSERT INTO departamentos (id, nombre, activo) VALUES
(1,  'Alto Paraguay',    true),
(2,  'Alto Paraná',      true),
(3,  'Amambay',          true),
(4,  'Boquerón',         true),
(5,  'Caaguazú',         true),
(6,  'Caazapá',          true),
(7,  'Canindeyú',        true),
(8,  'Capital',          true),
(9,  'Central',          true),
(10, 'Concepción',       true),
(11, 'Cordillera',       true),
(12, 'Guairá',           true),
(13, 'Itapúa',           true),
(14, 'Misiones',         true),
(15, 'Ñeembucú',         true),
(16, 'Paraguarí',        true),
(17, 'Presidente Hayes', true),
(18, 'San Pedro',        true)
ON CONFLICT (id) DO NOTHING;

-- CIUDADES
INSERT INTO ciudades (id, nombre, departamento_id, activo) VALUES
-- Alto Paraguay (1)
(1,   'Bahía Negra',                         1,  true),
(2,   'Capitán Carmelo Peralta',              1,  true),
(3,   'Fuerte Olimpo',                        1,  true),
(4,   'La Victoria',                          1,  true),
-- Alto Paraná (2)
(5,   'Ciudad del Este',                      2,  true),
(6,   'Doctor Juan León Mallorquín',          2,  true),
(7,   'Domingo Martínez de Irala',            2,  true),
(8,   'Hernandarias',                         2,  true),
(9,   'Iruña',                                2,  true),
(10,  'Itakyry',                              2,  true),
(11,  'Juan Emilio O''Leary',                 2,  true),
(12,  'Los Cedrales',                         2,  true),
(13,  'Mbaracayú',                            2,  true),
(14,  'Minga Guazú',                          2,  true),
(15,  'Minga Porã',                           2,  true),
(16,  'Naranjal',                             2,  true),
(17,  'Ñacunday',                             2,  true),
(18,  'Presidente Franco',                    2,  true),
(19,  'San Alberto',                          2,  true),
(20,  'San Cristóbal',                        2,  true),
(21,  'Santa Fe del Paraná',                  2,  true),
(22,  'Santa Rita',                           2,  true),
(23,  'Santa Rosa del Monday',                2,  true),
(24,  'Tavapy',                               2,  true),
(25,  'Yguazú',                               2,  true),
(246, 'Limoy',                                2,  true),
-- Amambay (3)
(26,  'Bella Vista',                          3,  true),
(27,  'Capitán Bado',                         3,  true),
(28,  'Pedro Juan Caballero',                 3,  true),
(29,  'Zanja Pytã',                           3,  true),
-- Boquerón (4)
(30,  'Filadelfia',                           4,  true),
(31,  'Loma Plata',                           4,  true),
(32,  'Mariscal Estigarribia',                4,  true),
(233, 'Infante Rivarola',                     4,  true),
-- Caaguazú (5)
(33,  'Caaguazú',                             5,  true),
(34,  'Carayaó',                              5,  true),
(35,  'Coronel Oviedo',                       5,  true),
(36,  'Doctor Cecilio Báez',                  5,  true),
(37,  'Doctor J. Eulogio Estigarribia',       5,  true),
(38,  'Doctor Juan Manuel Frutos',            5,  true),
(39,  'José Domingo Ocampos',                 5,  true),
(40,  'La Pastora',                           5,  true),
(41,  'Mcal. Francisco S. López',             5,  true),
(42,  'Nueva Londres',                        5,  true),
(43,  'Nueva Toledo',                         5,  true),
(44,  'R.I. Tres Corrales',                   5,  true),
(45,  'Raúl Arsenio Oviedo',                  5,  true),
(46,  'Repatriación',                         5,  true),
(47,  'San Joaquín',                          5,  true),
(48,  'San José de los Arroyos',              5,  true),
(49,  'Santa Rosa del Mbutuy',                5,  true),
(50,  'Simón Bolívar',                        5,  true),
(51,  'Tembiaporã',                           5,  true),
(52,  'Tres de Febrero',                      5,  true),
(53,  'Vaquería',                             5,  true),
(54,  'Yhu',                                  5,  true),
-- Caazapá (6)
(55,  '3 de Mayo',                            6,  true),
(56,  'Abay',                                 6,  true),
(57,  'Buena Vista',                          6,  true),
(58,  'Caazapá',                              6,  true),
(59,  'Doctor Moisés S. Bertoni',             6,  true),
(60,  'Fulgencio Yegros',                     6,  true),
(61,  'General Higinio Morínigo',             6,  true),
(62,  'Maciel',                               6,  true),
(63,  'San Juan Nepomuceno',                  6,  true),
(64,  'Tavay',                                6,  true),
(65,  'Yuty',                                 6,  true),
-- Canindeyú (7)
(66,  'Corpus Christi',                       7,  true),
(67,  'Curuguaty',                            7,  true),
(68,  'Gral. Francisco Caballero Álvarez',    7,  true),
(69,  'Itanaryi',                             7,  true),
(70,  'Katueté',                              7,  true),
(71,  'La Paloma',                            7,  true),
(72,  'Nueva Esperanza',                      7,  true),
(73,  'Salto del Guairá',                     7,  true),
(74,  'Villa Ygatimí',                        7,  true),
(75,  'Yasy Cañy',                            7,  true),
(76,  'Ybyrarovaní',                          7,  true),
(77,  'Ypejhú',                               7,  true),
-- Capital (8)
(78,  'Asunción',                             8,  true),
-- Central (9)
(79,  'Areguá',                               9,  true),
(80,  'Capiatá',                              9,  true),
(81,  'Fernando de la Mora',                  9,  true),
(82,  'Guarambaré',                           9,  true),
(83,  'Itá',                                  9,  true),
(84,  'Itauguá',                              9,  true),
(85,  'Julián Augusto Saldívar',              9,  true),
(86,  'Lambaré',                              9,  true),
(87,  'Limpio',                               9,  true),
(88,  'Luque',                                9,  true),
(89,  'Mariano Roque Alonso',                 9,  true),
(90,  'Nueva Italia',                         9,  true),
(91,  'Ñemby',                                9,  true),
(92,  'San Antonio',                          9,  true),
(93,  'San Lorenzo',                          9,  true),
(94,  'Villa Elisa',                          9,  true),
(95,  'Villeta',                              9,  true),
(96,  'Ypacaraí',                             9,  true),
(97,  'Ypané',                                9,  true),
-- Concepción (10)
(98,  'Azotey',                               10, true),
(99,  'Belén',                                10, true),
(100, 'Concepción',                           10, true),
(101, 'Horqueta',                             10, true),
(102, 'Loreto',                               10, true),
(103, 'San Carlos del Apa',                   10, true),
(104, 'San Lázaro',                           10, true),
(105, 'Sargento José Félix López',            10, true),
(106, 'Yby Yaú',                              10, true),
-- Cordillera (11)
(107, 'Altos',                                11, true),
(108, 'Arroyos y Esteros',                    11, true),
(109, 'Atyrá',                                11, true),
(110, 'Caacupé',                              11, true),
(111, 'Caraguatay',                           11, true),
(112, 'Emboscada',                            11, true),
(113, 'Eusebio Ayala',                        11, true),
(114, 'Isla Pucú',                            11, true),
(115, 'Itacurubí de la Cordillera',           11, true),
(116, 'Juan de Mena',                         11, true),
(117, 'Loma Grande',                          11, true),
(118, 'Mbocayaty del Yhaguy',                 11, true),
(119, 'Nueva Colombia',                       11, true),
(120, 'Piribebuy',                            11, true),
(121, 'Primero de Marzo',                     11, true),
(122, 'San Bernardino',                       11, true),
(123, 'San José Obrero',                      11, true),
(124, 'Santa Elena',                          11, true),
(125, 'Tobatí',                               11, true),
(126, 'Valenzuela',                           11, true),
-- Guairá (12)
(127, 'Borja',                                12, true),
(128, 'Coronel Martínez',                     12, true),
(129, 'Dr. Bottrell',                         12, true),
(130, 'Fassardi',                             12, true),
(131, 'Félix Pérez Cardozo',                  12, true),
(132, 'Garay',                                12, true),
(133, 'Independencia',                        12, true),
(134, 'Itapé',                                12, true),
(135, 'Iturbe',                               12, true),
(136, 'Mbocayaty',                            12, true),
(137, 'Natalicio Talavera',                   12, true),
(138, 'Ñumí',                                 12, true),
(139, 'Paso Yobái',                           12, true),
(140, 'San Salvador',                         12, true),
(141, 'Tebicuary',                            12, true),
(142, 'Troche',                               12, true),
(143, 'Villarrica',                           12, true),
(144, 'Yataity',                              12, true),
-- Itapúa (13)
(145, 'Alto Verá',                            13, true),
(146, 'Bella Vista',                          13, true),
(147, 'Cambyretá',                            13, true),
(148, 'Capitán Meza',                         13, true),
(149, 'Capitán Miranda',                      13, true),
(150, 'Carlos Antonio López',                 13, true),
(151, 'Carmen del Paraná',                    13, true),
(152, 'Coronel Bogado',                       13, true),
(153, 'Edelira',                              13, true),
(154, 'Encarnación',                          13, true),
(155, 'Fram',                                 13, true),
(156, 'General Artigas',                      13, true),
(157, 'General Delgado',                      13, true),
(158, 'Hohenau',                              13, true),
(159, 'Itapúa Poty',                          13, true),
(160, 'Jesús',                                13, true),
(161, 'José Leandro Oviedo',                  13, true),
(162, 'La Paz',                               13, true),
(163, 'Mayor Otaño',                          13, true),
(164, 'Natalio',                              13, true),
(165, 'Nueva Alborada',                       13, true),
(166, 'Obligado',                             13, true),
(167, 'Pirapó',                               13, true),
(168, 'San Cosme y Damián',                   13, true),
(169, 'San Juan del Paraná',                  13, true),
(170, 'San Pedro del Paraná',                 13, true),
(171, 'San Rafael del Paraná',                13, true),
(172, 'Tomás Romero Pereira',                 13, true),
(173, 'Trinidad',                             13, true),
(174, 'Yatytay',                              13, true),
-- Misiones (14)
(175, 'Ayolas',                               14, true),
(176, 'San Ignacio',                          14, true),
(177, 'San Juan Bautista',                    14, true),
(178, 'San Miguel',                           14, true),
(179, 'San Patricio',                         14, true),
(180, 'Santa María',                          14, true),
(181, 'Santa Rosa',                           14, true),
(182, 'Santiago',                             14, true),
(183, 'Villa Florida',                        14, true),
(184, 'Yabebyry',                             14, true),
-- Ñeembucú (15)
(185, 'Alberdi',                              15, true),
(186, 'Cerrito',                              15, true),
(187, 'Desmochados',                          15, true),
(188, 'General José Eduvigis Díaz',           15, true),
(189, 'Guazú Cuí',                            15, true),
(190, 'Humaitá',                              15, true),
(191, 'Isla Umbú',                            15, true),
(192, 'Laureles',                             15, true),
(193, 'Mayor Josúe J. Martínez',              15, true),
(194, 'Paso de Patria',                       15, true),
(195, 'Pilar',                                15, true),
(196, 'San Juan Bautista del Ñeembucú',       15, true),
(197, 'Tacuaras',                             15, true),
(198, 'Villa Franca',                         15, true),
(199, 'Villa Oliva',                          15, true),
(200, 'Villalbán',                            15, true),
-- Paraguarí (16)
(201, 'Acahay',                               16, true),
(202, 'Caapucú',                              16, true),
(203, 'Carapeguá',                            16, true),
(204, 'Escobar',                              16, true),
(205, 'Gral. Bernardino Caballero',           16, true),
(206, 'La Colmena',                           16, true),
(207, 'Mbuyapey',                             16, true),
(208, 'Paraguarí',                            16, true),
(209, 'Pirayú',                               16, true),
(210, 'Quiindy',                              16, true),
(211, 'Quyquyhó',                             16, true),
(212, 'San Roque González de Santa Cruz',     16, true),
(213, 'Sapucai',                              16, true),
(214, 'Tebicuarymí',                          16, true),
(215, 'Yaguarón',                             16, true),
(216, 'Ybycuí',                               16, true),
(217, 'Ybytymí',                              16, true),
-- Presidente Hayes (17)
(218, 'Benjamín Aceval',                      17, true),
(219, 'Dr. José Falcón',                      17, true),
(220, 'General José María Bruguez',           17, true),
(221, 'Nanawa',                               17, true),
(222, 'Puerto Pinasco',                       17, true),
(223, 'Tte. Esteban Martínez',               17, true),
(224, 'Tte. Irala Fernández',                17, true),
(225, 'Villa Hayes',                          17, true),
-- San Pedro (18)
(0,   'San Pedro del Ycuamandyyú',            18, true),
(226, 'Antequera',                            18, true),
(227, 'Capiibary',                            18, true),
(228, 'Choré',                                18, true),
(229, 'General Elizardo Aquino',              18, true),
(230, 'General Isidoro Resquín',              18, true),
(231, 'Guayaibí',                             18, true),
(232, 'Itacurubí del Rosario',                18, true),
(234, 'Lima',                                 18, true),
(235, 'Nueva Germania',                       18, true),
(236, 'San Estanislao',                       18, true),
(237, 'San Pablo',                            18, true),
(238, 'San Pedro',                            18, true),
(239, 'Santa Rosa del Aguaray',               18, true),
(240, 'Tacuatí',                              18, true),
(241, 'Unión',                                18, true),
(242, 'Veinticinco de Diciembre',             18, true),
(243, 'Villa del Rosario',                    18, true),
(244, 'Yataity del Norte',                    18, true),
(245, 'Yrybucuí',                             18, true),
(250, 'Santaní',                              18, true)
ON CONFLICT (id) DO NOTHING;

-- Verificación
SELECT 'departamentos' AS tabla, COUNT(*) AS registros FROM departamentos
UNION ALL
SELECT 'ciudades', COUNT(*) FROM ciudades;
